# services/Backend/services/business/pdf_generator.py — Official PDF Complaint Generator for Hermes & Backend
import io
import os
import logging
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

logger = logging.getLogger(__name__)

def generate_legal_pdf(report_id: int, db_session=None) -> io.BytesIO:
    """
    Generate an official legal complaint PDF document for city administration/utilities.
    Returns a BytesIO buffer containing the PDF file.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#0F172A'),
        alignment=TA_LEFT,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        fontName='Helvetica'
    )

    bold_style = ParagraphStyle(
        'DocBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )

    elements = []

    # Header Title
    elements.append(Paragraph("ОФИЦИАЛЬНОЕ ОБРАЩЕНИЕ В АДМИНИСТРАЦИЮ / ЖКХ", title_style))
    elements.append(Paragraph("Муниципальный мониторинг «City Pulse / СообщиО» (Нижневартовск)", body_style))
    elements.append(Spacer(1, 10))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#0284C7'), spaceBefore=5, spaceAfter=15))

    # Metadata Table
    date_str = datetime.now().strftime("%d.%m.%Y %H:%M")
    data = [
        [Paragraph("Регистрационный номер:", bold_style), Paragraph(f"№CP-{report_id:06d}", body_style)],
        [Paragraph("Дата создания:", bold_style), Paragraph(date_str, body_style)],
        [Paragraph("Муниципальное образование:", bold_style), Paragraph("г. Нижневартовск (ХМАО-Югра)", body_style)],
        [Paragraph("Статус обращения:", bold_style), Paragraph("ЗАРЕГИСТРИРОВАНО", bold_style)],
    ]

    t = Table(data, colWidths=[160, 340])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 15))

    # Legal Body Content
    elements.append(Paragraph("Суть муниципального обращения:", bold_style))
    elements.append(Spacer(1, 6))
    
    desc_text = (
        f"По данному сигналу №{report_id} зафиксировано нарушение правил благоустройства и коммунального обслуживания. "
        "Требуется выездная проверка уполномоченных служб администрации г. Нижневартовска и вынесение предписания УК."
    )
    elements.append(Paragraph(desc_text, body_style))
    elements.append(Spacer(1, 20))

    # Stamp box
    stamp_text = Paragraph(
        "✔ ЭЛЕКТРОННЫЙ ДОКУМЕНТ СФОРМИРОВАН ИИ-ГЕРМЕС<br/>"
        f"Идентификатор проверки: CP-VERIFY-{report_id}-{int(datetime.now().timestamp())}",
        ParagraphStyle('Stamp', parent=body_style, fontSize=8, textColor=colors.HexColor('#0284C7'), alignment=TA_CENTER)
    )
    stamp_table = Table([[stamp_text]], colWidths=[500])
    stamp_table.setStyle(TableStyle([
        ('BOX', (0, 0), (-1, -1), 1.5, colors.HexColor('#0284C7')),
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F0FDFA')),
        ('PADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(stamp_table)

    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_custom_pdf(title: str, body_text: str, address: str = "г. Нижневартовск") -> io.BytesIO:
    """
    Generate an official PDF document from custom text generated by Hermes AI Assistant.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#0F172A'),
        alignment=TA_LEFT,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        fontName='Helvetica'
    )

    bold_style = ParagraphStyle(
        'DocBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )

    elements = []

    # Header Title
    elements.append(Paragraph("ОФИЦИАЛЬНОЕ ЮРИДИЧЕСКОЕ ОБРАЩЕНИЕ", title_style))
    elements.append(Paragraph("Муниципальный портал «City Pulse / СообщиО» (Нижневартовск)", body_style))
    elements.append(Spacer(1, 10))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#0284C7'), spaceBefore=5, spaceAfter=15))

    # Metadata Table
    date_str = datetime.now().strftime("%d.%m.%Y %H:%M")
    doc_id = int(datetime.now().timestamp() * 1000) % 1000000
    data = [
        [Paragraph("Документ:", bold_style), Paragraph(title or "Официальная претензия", body_style)],
        [Paragraph("Дата и время:", bold_style), Paragraph(date_str, body_style)],
        [Paragraph("Адрес / Объект:", bold_style), Paragraph(address or "г. Нижневартовск", body_style)],
        [Paragraph("Статус:", bold_style), Paragraph("СФОРМИРОВАНО ИИ-ГЕРМЕС", bold_style)],
    ]

    t = Table(data, colWidths=[140, 360])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 15))

    # Legal Body Content
    elements.append(Paragraph("Текст заявления / обращения:", bold_style))
    elements.append(Spacer(1, 6))
    
    # Split paragraphs
    for line in body_text.split("\n"):
        line = line.strip()
        if line:
            clean_line = line.replace("**", "").replace("*", "").replace("#", "").strip()
            elements.append(Paragraph(clean_line, body_style))
            elements.append(Spacer(1, 4))
            
    elements.append(Spacer(1, 15))

    # Stamp box
    stamp_text = Paragraph(
        "✔ ЭЛЕКТРОННЫЙ ДОКУМЕНТ СФОРМИРОВАН ИИ-ГЕРМЕС<br/>"
        f"Идентификатор проверки: CP-VERIFY-{doc_id}",
        ParagraphStyle('Stamp', parent=body_style, fontSize=8, textColor=colors.HexColor('#0284C7'), alignment=TA_CENTER)
    )
    stamp_table = Table([[stamp_text]], colWidths=[500])
    stamp_table.setStyle(TableStyle([
        ('BOX', (0, 0), (-1, -1), 1.5, colors.HexColor('#0284C7')),
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F0FDFA')),
        ('PADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(stamp_table)

    doc.build(elements)
    buffer.seek(0)
    return buffer
